## Introduction to Numpy
* Numerical Python
* Linear Algebra for Python
* Has bindings to C library
* High Performance Scientific Computing

Numpy ndarray - A multidimensional Array Object
* HOMOGENOUES DATA

In [1]:
import numpy as np

In [ ]:
# Numpy gives metrix like architecture

In [2]:
n = np.array(range(1, 11))

In [3]:
# 1 Dimensional - 10 Rows & 1 column
n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
n.ndim

1

In [5]:
n.shape  # 10 rows

(10,)

In [6]:
### 2-D data  -- 1 row & 10 Columns

n2 = np.array([range(1, 11)])

In [7]:
n2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [8]:
n2.shape

(1, 10)

In [9]:
n2.ndim

2

In [10]:
n2.dtype

dtype('int32')

In [ ]:
# by default data type is int32

In [11]:
n.dtype

dtype('int32')

In [12]:
n_type = np.array([1,2,3,4,5,6,7,8,9,10],dtype='float')

In [13]:
n_type.dtype

dtype('float64')

### object data type array

In [15]:
# shape of list items are diff
lst_odd_size = [[1, 2, 3], [4, 5], [7, 8, 9]]
lst_odd_size

[[1, 2, 3], [4, 5], [7, 8, 9]]

In [16]:
md_arr_odd = np.array(lst_odd_size)

C:\Users\virka\AppData\Local\Temp/ipykernel_15336/2156717244.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  md_arr_odd = np.array(lst_odd_size)


In [17]:
md_arr_odd

array([list([1, 2, 3]), list([4, 5]), list([7, 8, 9])], dtype=object)

In [18]:
md_arr_odd.shape

# 3 rows

(3,)

In [19]:
md_arr_odd.ndim

# 1 Dim - 3 rows

1

In [20]:
md_arr_odd.dtype

dtype('O')

### Reshape - converting to diff dimension
    
    * assigning New Shape ex original shape (6,) -- rows x colums =6 --> (2,3),(3,2),(1,6) 
    * when you dont know the column size --- mention -1
    
    * reshape(pairs,rows,columns)
    * original (rows x column ) = reshaped (rows x column )

In [23]:
l=[1, 2, 3, 4, 5, 6]

arr=np.array(l)
arr

array([1, 2, 3, 4, 5, 6])

In [24]:
arr.shape

(6,)

In [25]:
# assigning New Shape  (6,) -- rows x colums =6 --> (2,3),(3,2),(1,6)   == INPLACE
arr.shape=(3,2)
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
l=[7,8,9,10,11,12]

arr2=np.array(l)
arr2

array([ 7,  8,  9, 10, 11, 12])

In [27]:
# reshape Method                 == Assign new variable
arr_new=arr2.reshape(2,3)
arr_new

array([[ 7,  8,  9],
       [10, 11, 12]])

In [28]:
### when you dont know the column size --- mention -1

arr_n=arr2.reshape(3,-1)
arr_n

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [29]:
reshaped_arr = arr2.reshape(4,-1)
reshaped_arr

ValueError: cannot reshape array of size 6 into shape (4,newaxis)

In [ ]:
# original (rows x column ) = reshaped (rows x column )

### Arange function

In [32]:
a=np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [33]:
a.shape=(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [34]:
# 6pairs of 4 rows & 1col
#reshape(pairs,rows,columns)

a.reshape(4,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [35]:
c = a.reshape(3, 2, 4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

### item size for each element

In [36]:
x = np.arange(6, dtype=np.int8)
x.itemsize

1

In [37]:
y = np.arange(6, dtype=np.int64)
y.itemsize

8

In [38]:
z = np.arange(6, dtype=np.int32)
z.itemsize

4

In [39]:
o = np.arange(6, dtype=object)
o.itemsize

8

In [40]:
f = np.arange(6, dtype=float)
f.itemsize

8

In [41]:
s = np.arange(6, dtype='S')
s.itemsize

ValueError: no fill-function for data-type.

###  Broadcasting

* Array slices are *actually* views on the original array
* That means, data isn't copied, and any modifications to the view would be reflected back to the source array

In [42]:
a=np.random.randint(10,30,10)
a

array([20, 21, 26, 13, 27, 21, 16, 24, 10, 16])

In [43]:
# taken a slice
a[:5]

array([20, 21, 26, 13, 27])

In [45]:
# reassigning possible in NP not in list
a[:5]=168

In [46]:
# reassigned array - this change is reflected in original array - 
a

array([168, 168, 168, 168, 168,  21,  16,  24,  10,  16])

In [47]:
a.dtype

dtype('int32')

In [48]:
len(a)

10

In [49]:
a[-1]

16

In [ ]:
# taking slice - assign to diff variable
# will it reflect in original array  -YES!!

In [50]:
new_a=a[:5]

In [51]:
new_a

array([168, 168, 168, 168, 168])

In [52]:
new_a[-3:]=77

In [53]:
new_a

array([168, 168,  77,  77,  77])

In [54]:
a

array([168, 168,  77,  77,  77,  21,  16,  24,  10,  16])

In [ ]:
# This is not possible in list
# in list change in slice is only limited to slice not to original list

### Matrix

In [55]:
#list to matrix
l=[[1,2,3],[5,6,7],[8,9,4]]
a=np.array(l)
a

array([[1, 2, 3],
       [5, 6, 7],
       [8, 9, 4]])

In [56]:
# Transpose
a.T

array([[1, 5, 8],
       [2, 6, 9],
       [3, 7, 4]])

In [57]:
#defining two matrix
c=np.array([[1,2],[3,4]],dtype=float)
d=np.array([[5,6],[7,8]],dtype=float)


In [58]:
c

array([[1., 2.],
       [3., 4.]])

In [ ]:
# 1 D - (r,)
# 2 D - ( r,c)
# 3 D - (pair,r,c)

#### Matrix Multiplication by -  DOT & MATMUL

* kindly note shape of matrix is crucial for multiplication
* no of columns of 1st = no of rows of 2nd

In [59]:
dotproduct=np.matmul(c,d)
dotproduct

array([[19., 22.],
       [43., 50.]])

In [60]:
dotproduct1=np.dot(c,d)
dotproduct1

array([[19., 22.],
       [43., 50.]])

In [64]:
# shape of array

a.shape

(3, 3)

#### Arthmetic Operations on Matrix

* element to elememt addition,multiplication,sub,div

In [61]:
c+d

array([[ 6.,  8.],
       [10., 12.]])

In [62]:
c-d

array([[-4., -4.],
       [-4., -4.]])

In [63]:
c/d

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [64]:
c*d

array([[ 5., 12.],
       [21., 32.]])

by Method

In [65]:
np.add(c,d)

array([[ 6.,  8.],
       [10., 12.]])

In [66]:
np.subtract(c,d)

array([[-4., -4.],
       [-4., -4.]])

In [67]:
np.multiply(c,d)

array([[ 5., 12.],
       [21., 32.]])

In [68]:
np.divide(c,d)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

#### Inverse of Matrix

In [69]:
a_inv=np.linalg.inv(a)
a_inv

array([[-1.625     ,  0.79166667, -0.16666667],
       [ 1.5       , -0.83333333,  0.33333333],
       [-0.125     ,  0.29166667, -0.16666667]])

In [ ]:
# AB=I=BA - ( I - Identity matrix ) then A & B are inverse

In [70]:
np.matmul(a,a_inv)

array([[ 1.00000000e+00,  1.11022302e-16,  2.77555756e-17],
       [ 9.71445147e-17,  1.00000000e+00, -8.32667268e-17],
       [ 5.55111512e-17,  4.44089210e-16,  1.00000000e+00]])

####  Trigonometry 

In [71]:
# thita - angle must be in pie=3.14
np.sin(3.14)

0.0015926529164868282

In [72]:
np.tan(0)

0.0

In [73]:
np.cos(0)

1.0

In [74]:
np.exp(1)

2.718281828459045

In [75]:
np.log10(10)

1.0

In [76]:
np.log(10)

2.302585092994046

### Basic Stats - Min Max Mean Median Var Std Quantile 

In [77]:
a.min()

1

In [81]:
np.min(a)

1

In [78]:
a.max()

9

In [82]:
np.max(a)

9

In [79]:
a.mean()

5.0

In [83]:
np.mean(a)

5.0

In [80]:
# only this way not by ---> a.median()
np.median(a)

5.0

In [84]:
np.var(a)

6.666666666666667

In [85]:
a.var()

6.666666666666667

In [86]:
np.std(a)

2.581988897471611

In [87]:
a.std()

2.581988897471611

In [88]:
# only this way not by ---> np.quantile(a,q=0.1)
np.quantile(a,q=0.25)

3.0

In [89]:
np.quantile(a,q=0.5)

5.0

In [90]:
np.quantile(a,q=0.75)

7.0

In [91]:
a

array([[1, 2, 3],
       [5, 6, 7],
       [8, 9, 4]])

In [92]:
np.max(a,axis=0)   # checks column wise - axis =1

array([8, 9, 7])

In [93]:
np.max(a,axis=1)   # checks row wise - axis =1

array([3, 7, 9])

In [ ]:
### by giving axis we can cal for that axis - Min Max Mean Median Var Std Quantile
###################   AXIS = 1  ---- ROW         In NP
###################   AXIS = 0 ---- COLUMN       in np

####  Indexing / Slicing 
* [    row        ,    column    ]
* [start:end:step, start:end:step]

In [94]:
a[0:2,0:3]

array([[1, 2, 3],
       [5, 6, 7]])

In [95]:
a[0:3,0:2]

array([[1, 2],
       [5, 6],
       [8, 9]])

In [96]:
a[0:3:2,0:3:2]

array([[1, 3],
       [8, 4]])

###  Concatenation 

* np.concatenate([a,b],axis=0/1)
* axis =1 ---- no of rows should be same    ---- side by side
* axis =0 ---- no of columns should be same ----   BELOW

In [97]:
a

array([[1, 2, 3],
       [5, 6, 7],
       [8, 9, 4]])

In [98]:
b=np.array([[5,9,2],[8,4,11],[3,7,17]])
b

array([[ 5,  9,  2],
       [ 8,  4, 11],
       [ 3,  7, 17]])

In [99]:
c

array([[1., 2.],
       [3., 4.]])

In [100]:
d

array([[5., 6.],
       [7., 8.]])

In [101]:
e=np.array([[5,9,2],[8,4,11]])
e

array([[ 5,  9,  2],
       [ 8,  4, 11]])

In [102]:
f=np.array([[5,9],[8,11],[7,17]])
f

array([[ 5,  9],
       [ 8, 11],
       [ 7, 17]])

#### Contatanation operation on same shape matrix 

In [103]:
con1=np.concatenate([a,b])  # bydefault axis = 0
con1  

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9,  4],
       [ 5,  9,  2],
       [ 8,  4, 11],
       [ 3,  7, 17]])

In [104]:
con2=np.concatenate([a,b],axis=1)       #### side by side
con2

array([[ 1,  2,  3,  5,  9,  2],
       [ 5,  6,  7,  8,  4, 11],
       [ 8,  9,  4,  3,  7, 17]])

In [105]:
con3=np.concatenate([a,b],axis=0)       #### below
con3

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9,  4],
       [ 5,  9,  2],
       [ 8,  4, 11],
       [ 3,  7, 17]])

#### Concatanation operation on diff shape matrix  -  both diffff

In [106]:
con4=np.concatenate([a,c],axis=0)       #### a is 3x3 , b is 2x2 - no of colmns not same - not possible
con4

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [107]:
con5=np.concatenate([a,c],axis=1)       #### side by side of 3x3 - not possible
con5

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

#### concatenation Operation when no of COLUMNS of both are same -------- axis =0 is possible

In [108]:
print( 'shape of a is -', np.shape(a))
print( 'shape of e is -', np.shape(e))

shape of a is - (3, 3)
shape of e is - (2, 3)


In [109]:
con6=np.concatenate([a,e],axis=0)       #### below of 3x3 - only possible
con6

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9,  4],
       [ 5,  9,  2],
       [ 8,  4, 11]])

In [110]:
con7=np.concatenate([a,e],axis=1)       #### side by side of 3x3 - not possible
con7

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

#### concatenate Operation when no of ROWS of both are same -------- axis =1 is possible

In [111]:
print( 'shape of a is -', np.shape(a))
print( 'shape of f is -', np.shape(f))

shape of a is - (3, 3)
shape of f is - (3, 2)


In [112]:
con7=np.concatenate([a,f],axis=1)       #### side by side of 3x3 - only possible
con7

array([[ 1,  2,  3,  5,  9],
       [ 5,  6,  7,  8, 11],
       [ 8,  9,  4,  7, 17]])

In [113]:
con7=np.concatenate([a,f],axis=0)       #### below of 3x3 - not possible
con7

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

### Methods on Array

* Zeros - shape 
* zeros_like (ref matrix)
* ones - shape
* ones_like (ref matrix)

In [114]:
#zeros((shape))
zero_a = np.zeros((3, 4))

In [115]:
zero_a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [116]:
## zeros_like((reference matrix for shape))
zero_like = np.zeros_like(f)
zero_like

array([[0, 0],
       [0, 0],
       [0, 0]])

In [117]:
one=np.ones((2,3))
one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [118]:
one_like=np.ones_like((f))
one_like

array([[1, 1],
       [1, 1],
       [1, 1]])

In [119]:
a = np.array([[1, 2], [2, 1]])
b = np.array([[2, 1], [1, 2]])

print(f'max from each position \n {np.maximum(a,b)}')    # np.max(array) - whole single matrix
print(f'min from each position \n {np.minimum(a,b)}')


max from each position 
 [[2 2]
 [2 2]]
min from each position 
 [[1 1]
 [1 1]]


In [120]:
#np.full((shape),value)
np.full((3,4),17)

array([[17, 17, 17, 17],
       [17, 17, 17, 17],
       [17, 17, 17, 17]])

In [121]:
# np.full_like((shape of reference),value) 
np.full_like((a),8)

array([[8, 8],
       [8, 8]])

In [122]:
b = np.arange(24).reshape(3, 4, 2)

In [123]:
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [124]:
# indexing - pair,rows,columns

b[2][0][0]

16

In [125]:
b[1][2][1]

13

In [126]:
c=np.arange(24).reshape(2,2,3,2)

In [127]:
c

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]]]])

In [128]:
c.ndim

4

In [129]:
#9  -- [ pair -- indexing , pair,row,clm ]
c[0][1][1][1]

9

In [130]:
#23
c[1][1][2][1]

23

### Stacking

In [131]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [132]:
b = np.hstack(a)
b

array([1, 2, 3, 4, 5, 6, 7, 8])

In [133]:
c = np.vstack(b)

In [134]:
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [135]:
d = np.vstack(a)
d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [136]:
### Stack  - Horizontal  - multiple matrix
d=np.array([10,11,12])
e=np.array([20,21,22])

f=np.hstack((d,e)) # sequence matters
f

array([10, 11, 12, 20, 21, 22])

In [137]:
f2=np.hstack((e,d)) # sequence matters
f2

array([20, 21, 22, 10, 11, 12])

In [138]:
v=np.vstack((d,e)) # sequence matters
v

array([[10, 11, 12],
       [20, 21, 22]])

In [139]:
stk = np.column_stack((d,e))
stk

array([[10, 20],
       [11, 21],
       [12, 22]])

In [140]:
d+e

array([30, 32, 34])

In [141]:
con=np.concatenate([d,e]) #hstack
con

array([10, 11, 12, 20, 21, 22])

#### Convert n-dim to 1d

In [2]:
arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
n_hstack = np.hstack(arr)
n_hstack

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
N_dim = arr.flatten()
N_dim

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### intersection (intersect1d) & difference(setdiff1d)

In [142]:
a = np.array([10, 20, 30, 40, 50, 60])
b = np.array([50, 60, 70, 80, 90])

np.intersect1d(a, b)

array([50, 60])

In [143]:
# a-b - unique in @a
np.setdiff1d(a, b)

array([10, 20, 30, 40])

In [144]:
# Sum (passing as list)

a = np.array([10, 11, 12])
b = np.array([20, 21, 22])

np.sum([a, b])

96

In [146]:
np.sum((a, b))

96

In [147]:
# column
np.sum([a, b], axis=0)

array([30, 32, 34])

In [148]:
# Row
np.sum([a, b], axis=1)

array([33, 63])

In [149]:
# Basic Math  - subtract

a=np.array([10,20,30])

a=a-5
a

array([ 5, 15, 25])

In [150]:
# Basic Math  - addition

a=np.array([10,20,30])

a=a+5
a

array([15, 25, 35])

In [151]:
# Basic Math  - Multiplication

a=np.array([10,20,30])

a=a*4
a

array([ 40,  80, 120])

In [152]:
# Basic Math  - Division

a=np.array([10,20,30])

a=a/2
a

array([ 5., 10., 15.])

In [153]:
# saving numpy
np.save('panks',a) # file name, mention which matrix to save here (a)

In [154]:
# loading 

b=np.load('panks.npy')
b

array([ 5., 10., 15.])

##  NUMPY TO PANDAS 

In [155]:
import pandas as pd 

pd.DataFrame(a)

#D&F capital kawali

0
0   5.0
1  10.0
2  15.0

In [156]:
pd.DataFrame(e)

0
0  20
1  21
2  22

In [ ]:
#numpy - matrix form
#pandas - Table(row &column)